"""create notes and note_reviews tables

Revision ID: f0e315aa0886
Revises: e3071d211553
Create Date: 2026-04-27 17:38:41.996061
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e315aa0886'
down_revision: Union[str, None] = 'e3071d211553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_reviews_note_id'), ['note_id'], unique=False)
        batch_op.create_unique_constraint('uq_note_reviewer', ['note_id', 'reviewer_id'])
        batch_op.create_foreign_key('fk_note_reviews_users', 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_note_reviews_notes', 'notes', ['note_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size_bytes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_index(batch_op.f('ix_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_foreign_key('fk_notes_rooms', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_notes_users', 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'rooms', ['room_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_notes_created_at'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('file_size_bytes')

    with op.batch_alter_table('note_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'notes', ['note_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewer_id'], ['id'])
        batch_op.drop_constraint('uq_note_reviewer', type_='unique')
        batch_op.drop_index(batch_op.f('ix_note_reviews_note_id'))

    # ### end Alembic commands ###
